#!/bin/bash

# Railway Persistent Storage Setup
# This script helps configure Railway to use persistent volumes for media uploads

echo "============================================"
echo "Railway Persistent Storage Setup Guide"
echo "============================================"
echo ""
echo "IMPORTANT: Railway's filesystem is ephemeral by default."
echo "Files uploaded to storage/app/public are lost on redeployment."
echo ""
echo "To fix this, you need to add a Railway Volume:"
echo ""
echo "Step 1: In Railway Dashboard"
echo "  1. Go to your project: https://railway.app/project/your-project"
echo "  2. Click on your service: TheGoodBeaconNewsOutlet"
echo "  3. Go to the 'Volumes' tab"
echo "  4. Click 'New Volume'"
echo "  5. Set:"
echo "     - Mount Path: /var/www/storage/app/public"
echo "     - Size: 10GB (or more if needed)"
echo "  6. Click 'Add Volume'"
echo ""
echo "Step 2: Redeploy"
echo "  - Railway will automatically redeploy with the persistent volume"
echo "  - All uploads will now persist across deployments!"
echo ""
echo "============================================"
echo "Alternative: Use S3/Cloudinary"
echo "============================================"
echo ""
echo "For production, consider using cloud storage:"
echo "  - AWS S3 (or S3-compatible like Cloudflare R2, DigitalOcean Spaces)"
echo "  - Cloudinary (image-specific)"
echo "  - Backblaze B2"
echo ""
echo "This provides:"
echo "  ✓ Better reliability"
echo "  ✓ CDN delivery"
echo "  ✓ Automatic backups"
echo "  ✓ No storage limits"
echo ""
echo "See STORAGE_SETUP.md for detailed instructions"
echo ""
